# -*- after-save-hook: org-latex-export-to-pdf; -*-

#+title: Programação Modular - Tic Tac Toe
#+author: Gabriel Bastos

#+options: title:nil date:nil H:5
#+language: bt-br

#+latex_header: \usepackage[a4paper, margin=2cm]{geometry}
#+latex_header: \usepackage[brazilian]{babel}
#+latex_header: \usepackage[bottom]{footmisc}
#+latex_header: \usepackage{float}
#+latex_header: \usepackage{svg}

#+latex_header: \usepackage{titling}
#+latex_header: \setlength{\droptitle}{-1.5cm}

#+latex_header: \usepackage{url}
#+latex_header: \urlstyle{same}

#+latex_header: \hypersetup{ colorlinks = true, urlcolor = blue, citecolor = black }

#+latex: \setlength\parindent{0pt}

# Title page:
#+begin_export latex
\begin{titlepage}
  \centering
  
  \vfill{
    \bfseries\Huge
    Universidade Federal de Minas Gerais\\[5pt]
    \bfseries\Large
    Bacharel em Sistemas de Informação \\
    Programação Modular\\
  }
  
  \vfill
  
  \includegraphics[width=13cm]{images/ufmg_logo.jpg}
  
  \vfill{
    \bfseries\Large
    Trabalho Prático 1\\
    Setembro 2018\\
  }
  \vfill{
    \bfseries\large
    Gabriel Silva Bastos\\[5pt]
    Matrícula: 2016058204
  }
\end{titlepage}
#+end_export

* Passeio do cavalo
  No trabalho prático, recebemos a tarefa de implementar um algoritmo para calcular o
  passeio do cavalo. O passeio do cavalo é um caminho que o cavalo percorre, cobrindo todo
  o tabuleiro de xadrez, partindo de uma casa inicial definida. O passeio só é válido se o
  cavalo percorrer todas as casas do tabuleiro.
* Algoritmo
  De acordo com a descrição do algoritmo a ser utilizado, implementei o código com a
  técnica de /backtracking/. Este explora todas as rotas, e retrocede caso um caminho sem
  saída seja alcançado antes de se completar o passeio. Ao completar o tabuleiro, o
  algoritmo chega em seu fim. Caso nenhum passeio completo seja encontrado, indica-se a
  impossibilidade deste.
* Arquitetura
  TODO insert observer design pattern here
** Diagrama UML
   [[./uml/diagram.pdf]]
